import Link from "next/link";
import { requireLearnUser } from "@/lib/learn-auth";
import { getBuilderProgress, getCredentialForUser, getProgress } from "@/lib/learn-db";
import { units } from "../course-data";
import { MintCredentialButton, RefreshMintStatusButton, TrackedConversionLink } from "../learner-actions";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";
export const metadata = { title: "My learning" };

export default async function DashboardPage() {
  const user = await requireLearnUser("/learn/dashboard");
  const progress = getProgress(user.id);
  const credential = getCredentialForUser(user.id);
  const builder = getBuilderProgress(user.id);
  const next = units.find((unit) => !progress.passedQuizzes.includes(unit.slug));
  const assessmentEligible = progress.passedQuizzes.length === units.length && progress.assessmentScore == null;
  const attempts = [
    ...progress.quizAttempts.map((attempt) => ({ kind: units.find((unit) => unit.slug === attempt.unitSlug)?.title || attempt.unitSlug, ...attempt })),
    ...progress.assessmentAttempts.map((attempt) => ({ kind: "Final assessment", unitSlug: "assessment", ...attempt })),
  ].sort((a, b) => b.attemptedAt.localeCompare(a.attemptedAt)).slice(0, 8);
  const explorerUrl = credential?.explorerUrl?.startsWith("https://") ? credential.explorerUrl : null;
  return <>
    <section className="flex flex-col justify-between gap-6 border-b border-black/10 pb-10 sm:flex-row sm:items-end"><div><p className="text-xs uppercase tracking-[0.18em] text-[#A50045]">Your Sokosumi-linked learning</p><h1 className="mt-3 text-5xl font-medium tracking-tight">Hello, {user.displayName || user.email?.split("@")[0] || "learner"}</h1><p className="mt-3 text-black/55">Progress and credentials belong to this account.</p></div><Link href="/learn/account" className="rounded-full border border-black/15 px-5 py-2.5 text-sm">Account and privacy</Link></section>
    <div className="mt-8 grid gap-5 lg:grid-cols-[1.25fr_0.75fr]">
      <section className="rounded-3xl bg-white p-7 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-2xl font-medium">Fundamentals</h2><span className="text-sm text-black/50">{progress.passedQuizzes.length} / {units.length} units</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-black/10"><div className="h-full bg-[#FA008C]" style={{ width: `${progress.passedQuizzes.length / units.length * 100}%` }} /></div><div className="mt-7 grid gap-3 sm:grid-cols-2">{units.map((unit) => <Link key={unit.slug} href={`/learn/${unit.slug}`} className="rounded-2xl border border-black/10 p-4 hover:border-[#FA008C]/50"><span className="text-xs text-black/45">Unit {unit.number}</span><strong className="mt-1 block font-medium">{unit.title}</strong><span className="mt-2 block text-xs text-[#A50045]">{progress.passedQuizzes.includes(unit.slug) ? `Passed · ${progress.quizScores[unit.slug]}%` : progress.completedLessons.includes(unit.slug) ? "Lesson complete" : "Not started"}</span></Link>)}</div>{next ? <Link href={`/learn/${next.slug}`} className="mt-7 inline-block rounded-full bg-black px-5 py-3 text-sm text-white">Continue: {next.title} →</Link> : <Link href="/learn/assessment" className="mt-7 inline-block rounded-full bg-black px-5 py-3 text-sm text-white">Open assessment →</Link>}</section>
      <section className="rounded-3xl bg-black p-7 text-white"><p className="text-xs uppercase tracking-[0.18em] text-white/45">Credential</p>{credential ? <><h2 className="mt-3 text-3xl font-medium">Masumi Fundamentals</h2><p className="mt-3 text-sm text-white/60">Issued {new Date(credential.issuedAt).toLocaleDateString()} · {credential.score}%</p><p className="mt-6 rounded-full bg-white/10 px-3 py-2 text-center text-xs uppercase tracking-widest">{credential.status.replaceAll("_", " ")}</p>{credential.status === "mint_failed" && <p role="alert" className="mt-3 text-sm leading-6 text-amber-200">The off-chain credential is safe. You can retry or reconcile the on-chain request.</p>}{credential.status === "revoked" && <p className="mt-3 text-sm leading-6 text-red-200">This credential has been revoked and cannot be minted.</p>}{credential.status === "superseded" && <p className="mt-3 text-sm leading-6 text-amber-200">A newer course-version credential replaced this one.</p>}<div className="mt-5 space-y-3"><Link href={`/learn/verify/${credential.id}`} className="block rounded-full bg-white px-5 py-3 text-center text-sm text-black">View public certificate</Link>{explorerUrl && <a href={explorerUrl} className="block rounded-full border border-white/25 px-5 py-3 text-center text-sm">View transaction ↗</a>}{(credential.status === "ready_to_mint" || credential.status === "mint_failed") && <MintCredentialButton />}{(credential.status === "minting" || credential.status === "mint_failed") && <RefreshMintStatusButton />}</div><p className="mt-5 text-xs leading-5 text-white/45">Minting is optional. Chain records are permanent and contain only the credential ID/hash, course/version, and issuer—not your name, email, OAuth data, or answers.</p></> : <><h2 className="mt-3 text-3xl font-medium">{assessmentEligible ? "Assessment ready" : progress.completedLessons.length ? "In progress" : "Not started"}</h2><p className="mt-3 text-sm leading-6 text-white/60">{assessmentEligible ? "You passed every unit quiz. Complete the final assessment to earn the credential." : "Pass every unit quiz and the final assessment. Eligibility is checked by the server."}</p>{assessmentEligible && <Link href="/learn/assessment" className="mt-5 block rounded-full bg-white px-5 py-3 text-center text-sm text-black">Take final assessment</Link>}</>}</section>
    </div>
    <section className="mt-5 rounded-3xl bg-white p-7 shadow-sm"><div className="flex items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.18em] text-[#A50045]">Attempt history</p><h2 className="mt-2 text-2xl font-medium">Recent knowledge checks</h2></div><span className="text-xs text-black/45">No answers retained</span></div>{attempts.length ? <ul className="mt-5 divide-y divide-black/10">{attempts.map((attempt, index) => <li key={`${attempt.unitSlug}-${attempt.attemptedAt}-${index}`} className="flex items-center justify-between gap-4 py-3 text-sm"><div><strong className="font-medium">{attempt.kind}</strong><span className="ml-2 text-black/45">{new Date(attempt.attemptedAt).toLocaleString()}</span></div><span className={attempt.passed ? "text-emerald-700" : "text-amber-700"}>{attempt.score}% · {attempt.passed ? "Passed" : "Review"}</span></li>)}</ul> : <p className="mt-5 rounded-2xl bg-black/[0.03] p-5 text-sm text-black/55">Your quiz and assessment attempts will appear here after the first submission.</p>}</section>
    {credential && <section className="mt-5 rounded-3xl bg-[#6400FF] p-7 text-white"><div className="grid gap-6 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="text-xs uppercase tracking-[0.18em] text-white/50">Builder path</p><h2 className="mt-2 text-3xl font-medium">{builder.credential ? "Masumi Builder earned" : builder.submission?.status === "verified" ? "Proof verified—finish Unit 6" : builder.completedSteps.length ? `${builder.completedSteps.length} of 6 project steps complete` : "Turn Fundamentals into a working integration"}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65">{builder.credential ? `Builder assessment ${builder.credential.score}% · ${builder.credential.status.replaceAll("_", " ")}` : "Build on Preprod, verify one payment without sharing secrets, and complete the operating assessment."}</p></div><Link href={builder.credential ? `/learn/verify/${builder.credential.id}` : "/learn/builder"} className="rounded-full bg-white px-5 py-3 text-center text-sm text-black">{builder.credential ? "View Builder certificate" : "Continue Builder path →"}</Link></div></section>}
    {credential && <section className="mt-5 grid gap-3 sm:grid-cols-2"><TrackedConversionLink href="https://www.masumi.network/dev/masumi/documentation/get-started/install-masumi-node" event="learn_docs_conversion" params={{ has_builder_credential: builder.credential ? 1 : 0 }}>Start your first Masumi integration →</TrackedConversionLink><TrackedConversionLink href="https://www.masumi.network/dev/masumi/documentation/how-to-guides/list-agent-on-sokosumi" event="learn_publish_conversion" params={{ has_builder_credential: builder.credential ? 1 : 0 }}>Prepare a service for Sokosumi →</TrackedConversionLink></section>}
  </>;
}
