import type { Locale } from "@/lib/i18n";

// Bilingual copy for /x402-protocol and /de/x402-protocol. The German was
// translated by a separate pass against the CORRECTED English, after the first
// draft of this page was found to document x402 v1 from memory. Protocol
// identifiers (x402, PAYMENT-REQUIRED, escrow, exact, facilitator, asset
// transfer method, ...) are deliberately left in English in both locales,
// because that is what German developers actually write.
type Entry = { en: string; de: string };

const COPY = {
  TITLE: { en: "x402 protocol: how HTTP 402 lets agents pay for a request", de: "x402-Protokoll: Wie Agents mit HTTP 402 für einen Request bezahlen" },
  DESCRIPTION: { en: "How x402 v2 works: the PAYMENT-REQUIRED, PAYMENT-SIGNATURE and PAYMENT-RESPONSE headers, the three payment flows, the schemes available, and where x402 sits next to AP2 and ACP.", de: "Funktionsweise von x402 v2: die Header PAYMENT-REQUIRED, PAYMENT-SIGNATURE und PAYMENT-RESPONSE, die drei Zahlungsabläufe, die verfügbaren Schemata und die Einordnung von x402 neben AP2 und ACP." },
  EYEBROW: { en: "The protocol · v2", de: "Das Protokoll · v2" },
  H1: { en: "x402: paying for a request over HTTP", de: "x402: Bezahlen eines Requests über HTTP" },
  LEDE: { en: "x402 lets a server answer a request with a price instead of a login, and a client pay it without an account. This page documents v2, where the payment terms travel in a PAYMENT-REQUIRED header rather than the response body — a change a lot of writing about x402, including an earlier version of this page, still gets wrong.", de: "Mit x402 kann ein Server einen Request mit einer Preisangabe statt einer Anmeldeaufforderung beantworten; der Client kann ohne Konto bezahlen. Diese Seite dokumentiert v2. Dort werden die Zahlungsbedingungen in einem PAYMENT-REQUIRED-Header statt im Response-Body übertragen. Viele Texte über x402 stellen das weiterhin falsch dar, auch eine frühere Fassung dieser Seite." },
  CTA_PRIMARY: { en: "Run the Cardano demo", de: "Cardano-Demo ausführen" },
  CTA_SECONDARY: { en: "Read the v2 specification", de: "v2-Spezifikation lesen" },
  H2_WIRE: { en: "On the wire", de: "Ablauf auf Protokollebene" },
  WIRE_INTRO: { en: "One unpaid request, one 402 carrying the terms, one paid retry. The headers are base64-encoded JSON; they are expanded here so you can see the fields.", de: "Ein unbezahlter Request, eine 402-Response mit den Bedingungen, ein bezahlter Retry. Die Header enthalten base64-kodiertes JSON; hier ist es dekodiert dargestellt, damit Sie die Felder sehen können." },
  H2_FLOWS: { en: "When the money moves", de: "Wann das Settlement erfolgt" },
  FLOWS_INTRO: { en: "Schemes differ in how a payment is formed. Payment flows differ in WHEN settlement happens relative to the server doing the work — which decides who carries the risk if the handler fails. A scheme declares a default per asset transfer method.", de: "Schemata unterscheiden sich darin, wie eine Zahlung erzeugt wird. Zahlungsabläufe unterscheiden sich darin, WANN das Settlement im Verhältnis zur Ausführung der Arbeit durch den Server erfolgt. Daraus ergibt sich, wer das Risiko trägt, wenn der Handler fehlschlägt. Ein Schema legt pro asset transfer method einen default fest." },
  H3_SCHEMES: { en: "And the schemes", de: "Die Schemata" },
  H2_STANDARDS: { en: "x402, AP2 and ACP", de: "x402, AP2 und ACP" },
  STANDARDS_INTRO: { en: "These are usually presented as rivals. They are layers, and they compose — AP2’s own examples use x402 as a payment method. Only one of the three settles anything.", de: "Diese Protokolle werden meist als Konkurrenten dargestellt. Tatsächlich liegen sie auf verschiedenen Ebenen und lassen sich kombinieren: Selbst die Beispiele von AP2 verwenden x402 als Zahlungsmethode. Nur eines der drei führt ein Settlement durch." },
  STANDARDS_NOTE: { en: "Not an exhaustive list. Stripe and Tempo’s Machine Payments Protocol and Google’s Universal Commerce Protocol also target parts of this space.", de: "Keine vollständige Liste. Auch das Machine Payments Protocol von Stripe und Tempo sowie das Universal Commerce Protocol von Google decken Teilbereiche dieses Feldes ab." },
  H2_LIMITS: { en: "Where x402 stops", de: "Grenzen von x402" },
  H2_FAQ: { en: "Questions", de: "Fragen" },
  H2_RELATED: { en: "Keep reading", de: "Weitere Informationen" },
  FLOW_AUTHORIZATION: { en: "The default. The facilitator checks the payment is good, the server does the work, then the payment commits. If the handler fails, nothing settles.", de: "Der default. Der facilitator prüft, ob die Zahlung gültig ist. Der Server führt die Arbeit aus, anschließend erfolgt das Settlement. Schlägt der Handler fehl, findet kein Settlement statt." },
  FLOW_UPFRONT: { en: "Payment commits before the work starts. Required on networks with no pull-settlement primitive. No /verify — settle establishes validity.", de: "Das Settlement erfolgt, bevor die Arbeit beginnt. Dieser Flow ist in Netzwerken ohne Pull-Settlement-Primitive erforderlich. Es gibt kein /verify; /settle stellt die Gültigkeit fest." },
  FLOW_ESCROW: { en: "A first settle commits a deposit or ceiling, the work runs, a second settle records the final charge. This is how metered and refundable payments are expressed.", de: "Ein erstes Settlement schreibt eine Einlage oder Obergrenze fest. Dann wird die Arbeit ausgeführt, und ein zweites Settlement hält den endgültigen Betrag fest. So werden verbrauchsabhängige und erstattungsfähige Zahlungen abgebildet." },
  SCHEME_EXACT: { en: "A fixed price, known before the work runs. The common case.", de: "Ein Festpreis, der vor Ausführung der Arbeit bekannt ist. Der Regelfall." },
  SCHEME_UPTO: { en: "A ceiling. The final charge is decided after the work, up to that maximum — metered billing.", de: "Eine Obergrenze. Der endgültige Betrag wird nach der Arbeit bis zu diesem Höchstwert festgelegt. Das ermöglicht eine verbrauchsabhängige Abrechnung." },
  SCHEME_AUTH_CAPTURE: { en: "Authorize now, capture later, with voids and refunds. The card-style two-step.", de: "Jetzt autorisieren, später einziehen, einschließlich Stornierungen und Erstattungen. Das zweistufige Verfahren einer Kartenzahlung." },
  SCHEME_BATCH_SETTLEMENT: { en: "Commit per request, move value later in aggregate. For volumes where per-request settlement costs more than the payment.", de: "Die Zahlung pro Request festschreiben, den Wert aber erst später gesammelt übertragen. Für Volumina, bei denen das Settlement pro Request mehr kostet als die Zahlung." },
  STD_X402_FROM: { en: "Coinbase; stewarded by the Linux Foundation's x402 Foundation", de: "Coinbase; betreut von der x402 Foundation der Linux Foundation" },
  STD_X402_LAYER: { en: "Payment negotiation and execution", de: "Zahlungsverhandlung und -ausführung" },
  STD_X402_SETTLES: { en: "Yes — via the scheme and facilitator", de: "Ja — über das Schema und den facilitator" },
  STD_X402_NOTE: { en: "How a server states a price and a client pays it, over HTTP, MCP or A2A.", de: "Wie ein Server über HTTP, MCP oder A2A einen Preis angibt und ein Client ihn bezahlt." },
  STD_AP2_FROM: { en: "Google; moved into FIDO standardization", de: "Google; in die Standardisierung bei FIDO überführt" },
  STD_AP2_LAYER: { en: "Authorization and evidence", de: "authorization und Nachweisführung" },
  STD_AP2_SETTLES: { en: "No — the chosen rail settles", de: "Nein — das Settlement erfolgt über den gewählten Zahlungsweg" },
  STD_AP2_NOTE: { en: "Linked Checkout and Payment Mandates recording what a human authorised. Payment-instrument agnostic; its examples include x402.", de: "Miteinander verknüpfte Checkout Mandate und Payment Mandate halten fest, was ein Mensch genehmigt hat. Sie sind unabhängig vom Zahlungsinstrument; zu ihren Beispielen gehört x402." },
  STD_ACP_FROM: { en: "OpenAI and Stripe", de: "OpenAI und Stripe" },
  STD_ACP_LAYER: { en: "Checkout and order interoperability", de: "Interoperabilität von Checkout und Bestellung" },
  STD_ACP_SETTLES: { en: "No — the merchant's PSP settles", de: "Nein — das PSP des Händlers führt das Settlement durch" },
  STD_ACP_NOTE: { en: "A versioned checkout and order API between an agent application and a seller, with idempotency and webhooks.", de: "Eine versionierte Checkout- und Bestell-API zwischen einer Agent-Anwendung und einem Verkäufer, mit Idempotenz und Webhooks." },
  LIMITS_P1: { en: "The protocol handles more than it is usually given credit for: the authorization flow only settles after the handler succeeds, escrow and auth-capture support deposits, voids and refunds, and an offer-and-receipt extension records what was promised. What it cannot do is judge whether the answer you got was correct. A server returning 200 with a bad result has satisfied every rule in the specification.", de: "Das Protokoll leistet mehr, als ihm meist zugeschrieben wird: Im authorization-Flow erfolgt das Settlement erst nach erfolgreichem Abschluss des Handlers; escrow und auth-capture unterstützen Einlagen, Stornierungen und Erstattungen; eine Angebots- und Belegerweiterung dokumentiert, was zugesagt wurde. Das Protokoll kann jedoch nicht beurteilen, ob die erhaltene Antwort korrekt war. Ein Server, der 200 mit einem schlechten Ergebnis zurückgibt, hat sämtliche Regeln der Spezifikation erfüllt." },
  LIMITS_P2: { en: "That judgement needs a party, a deadline and a record. On Cardano the exact scheme defines three asset transfer methods — default, masumi and script — and the masumi method is the one that adds refund mechanics and decentralised decision logging on top of the payment. The Cardano binding defines all three; our Cardano page covers what Masumi changes and what its dispute path actually requires.", de: "Diese Beurteilung erfordert eine Partei, eine Frist und eine Aufzeichnung. Auf Cardano definiert das Schema exact drei Varianten der asset transfer method: default, masumi und script. Die Variante masumi ergänzt die Zahlung um Erstattungsmechanik und dezentralisierte Entscheidungsprotokollierung. Das Cardano-Binding definiert alle drei; unsere Cardano-Seite erläutert, was Masumi ändert und welche Anforderungen das zugehörige Streitbeilegungsverfahren tatsächlich stellt." },
  FAQ1_Q: { en: "What is the x402 protocol?", de: "Was ist das x402-Protokoll?" },
  FAQ1_A: { en: "An open, Apache-licensed protocol for negotiating and executing a payment for a resource. Its HTTP transport uses the 402 status code plus three headers; it also has MCP and A2A transports. A server answers with the payments it accepts, the client signs one and retries, and the server returns the resource along with the settlement result.", de: "Ein offenes, unter der Apache-Lizenz stehendes Protokoll zur Verhandlung und Ausführung einer Zahlung für eine Ressource. Der HTTP-Transport verwendet den Statuscode 402 und drei Header; außerdem gibt es Transporte für MCP und A2A. Ein Server antwortet mit den akzeptierten Zahlungsoptionen, der Client signiert eine davon und sendet den Request erneut. Der Server gibt die Ressource zusammen mit dem Settlement-Ergebnis zurück." },
  FAQ2_Q: { en: "What is HTTP 402?", de: "Was ist HTTP 402?" },
  FAQ2_A: { en: "A status code reserved for payment in the original HTTP specification and left effectively unused for three decades. In x402 v2 the 402 signals that payment is required; the terms themselves travel in the PAYMENT-REQUIRED header, base64-encoded, not in the response body.", de: "Ein Statuscode, der bereits in der ursprünglichen HTTP-Spezifikation für Zahlungen reserviert war und drei Jahrzehnte lang praktisch ungenutzt blieb. In x402 v2 signalisiert 402, dass eine Zahlung erforderlich ist. Die Bedingungen selbst werden base64-kodiert im Header PAYMENT-REQUIRED und nicht im Response-Body übertragen." },
  FAQ3_Q: { en: "Which headers does x402 v2 use?", de: "Welche Header verwendet x402 v2?" },
  FAQ3_A: { en: "PAYMENT-REQUIRED carries the server's accepted payments. PAYMENT-SIGNATURE carries the client's signed payload — an authorization, not proof that settlement finished. PAYMENT-RESPONSE carries the settlement result back. The v1 X-PAYMENT header is legacy; a good deal of writing about x402 still describes it, including the earlier version of this page.", de: "PAYMENT-REQUIRED enthält die vom Server akzeptierten Zahlungsoptionen. PAYMENT-SIGNATURE enthält die signierte Payload des Clients — eine authorization, keinen Nachweis über den Abschluss des Settlements. PAYMENT-RESPONSE übermittelt das Settlement-Ergebnis zurück. Der Header X-PAYMENT aus v1 ist veraltet; viele Texte über x402 beschreiben ihn weiterhin, auch die frühere Fassung dieser Seite." },
  FAQ4_Q: { en: "Does the client pay before or after the server does the work?", de: "Bezahlt der Client, bevor oder nachdem der Server die Arbeit ausführt?" },
  FAQ4_A: { en: "It depends on the resolved payment flow, and this is the detail most summaries get wrong. The default, authorization, verifies first and settles after the handler succeeds. upfront settles before the work runs. escrow settles twice, around it. A resource offering both authorization and a pre-handler flow expects clients to prefer authorization.", de: "Das hängt vom ermittelten Zahlungsablauf ab, und genau dieses Detail stellen die meisten Zusammenfassungen falsch dar. Der Standard-Flow authorization prüft zuerst und führt das Settlement erst nach erfolgreichem Abschluss des Handlers aus. upfront führt das Settlement vor der Arbeit aus. escrow führt es zweimal aus, davor und danach. Bietet eine Ressource sowohl authorization als auch einen Flow mit Settlement vor dem Handler an, wird erwartet, dass Clients authorization bevorzugen." },
  FAQ5_Q: { en: "Does x402 require crypto?", de: "Erfordert x402 Kryptowährungen?" },
  FAQ5_A: { en: "Not by specification. v2 is rail- and asset-agnostic, permits ISO 4217 fiat assets, and has an official batch-settlement binding that bills off-chain in USD. In practice most deployments today settle on-chain in stablecoins, because that clears in seconds without a merchant account.", de: "Laut Spezifikation nicht. v2 ist unabhängig von Zahlungsweg und Asset, unterstützt Fiatwährungen nach ISO 4217 und verfügt über ein offizielles batch-settlement-Binding, das off-chain in USD abrechnet. In der Praxis erfolgt das Settlement bei den meisten heutigen Implementierungen on-chain über Stablecoin-Transaktionen, weil die Abwicklung damit in Sekunden und ohne Händlerkonto möglich ist." },
  FAQ6_Q: { en: "x402, AP2 or ACP — which do I need?", de: "x402, AP2 oder ACP — was benötige ich?" },
  FAQ6_A: { en: "They sit at different layers and compose rather than compete. x402 negotiates and executes the payment. AP2 records what a human authorised their agent to do, and produces dispute evidence without adjudicating disputes. ACP gives a seller a checkout and order API for agent traffic. An agent buying an API call needs x402; an agent spending someone's money on their behalf likely needs AP2 alongside it.", de: "Sie liegen auf verschiedenen Ebenen und lassen sich kombinieren, statt miteinander zu konkurrieren. x402 verhandelt die Zahlung und führt sie aus. AP2 hält fest, wozu ein Mensch seinen Agent bevollmächtigt hat, und erstellt Nachweise für Streitfälle, ohne diese zu entscheiden. ACP stellt einem Verkäufer eine Checkout- und Bestell-API für Anfragen von Agents bereit. Ein Agent, der einen API-Aufruf kauft, benötigt x402. Ein Agent, der im Auftrag einer Person deren Geld ausgibt, benötigt voraussichtlich zusätzlich AP2." },
  FAQ7_Q: { en: "What does x402 not do?", de: "Was leistet x402 nicht?" },
  FAQ7_A: { en: "It does not judge whether what you bought was any good. Settlement can be bound to the handler executing successfully, and the offer-and-receipt extension records what was promised — but a server that returns 200 with a poor answer has satisfied the protocol. Quality disputes need something above it, which is where escrow with a real dispute path comes in.", de: "x402 beurteilt nicht die Qualität des Gekauften. Das Settlement kann an die erfolgreiche Ausführung des Handlers gebunden werden, und die Angebots- und Belegerweiterung dokumentiert, was zugesagt wurde. Ein Server, der 200 mit einer schlechten Antwort zurückgibt, hat das Protokoll dennoch erfüllt. Qualitätsstreitfälle benötigen eine darüberliegende Schicht; hier ist escrow mit einem tatsächlichen Streitbeilegungsverfahren erforderlich." },
  REL__X402_TITLE: { en: "x402 on Cardano", de: "x402 auf Cardano" },
  REL__X402_NOTE: { en: "The masumi asset transfer method, and a payment you can run on mainnet.", de: "Die asset transfer method masumi und eine Zahlung, die Sie im Mainnet ausführen können." },
  REL__GLOSSARY_X402_TITLE: { en: "x402 in the glossary", de: "x402 im Glossar" },
  REL__GLOSSARY_X402_NOTE: { en: "The short definition, with the neighbouring terms.", de: "Die Kurzdefinition mit den verwandten Begriffen." },
  REL__GLOSSARY_TITLE: { en: "Agentic payments glossary", de: "Glossar zu Agent-Zahlungen" },
  REL__GLOSSARY_NOTE: { en: "AP2, A2A, escrow, DIDs and the rest of the vocabulary.", de: "AP2, A2A, escrow, DIDs und die übrigen Begriffe." },
} satisfies Record<string, Entry>;

export type CopyKey = keyof typeof COPY;

// Several call sites build keys dynamically (FAQ1_Q, FLOW_ESCROW, STD_AP2_NOTE).
// Those cannot be checked at compile time, so a missing key throws here rather
// than rendering an empty element that nobody notices until it is live.
export function t(locale: Locale) {
  return (key: CopyKey | string): string => {
    const entry = (COPY as Record<string, Entry | undefined>)[key];
    if (!entry) throw new Error(`x402-protocol copy: no such key "${key}"`);
    return entry[locale] || entry.en;
  };
}
