import Link from "next/link";
import { getCurrentLearnUser } from "@/lib/learn-auth";
import { getProgress } from "@/lib/learn-db";
import { units } from "./course-data";
import { TrackedLink } from "./learner-actions";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";
export const metadata = { alternates: { canonical: "/learn" }, title: "Learn", description: "Become a certified Masumi developer with the free Masumi Fundamentals course and a verifiable, optionally on-chain certificate." };

export default async function LearnPage({ searchParams }: { searchParams: Promise<{ signedOut?: string }> }) {
  const params = await searchParams;
  const user = await getCurrentLearnUser();
  const progress = user ? getProgress(user.id) : null;
  const name = user ? user.displayName || user.email?.split("@")[0] || "learner" : null;
  const next = progress ? units.find((unit) => !progress.passedQuizzes.includes(unit.slug)) : null;
  const signedOut = !user && params.signedOut === "1";

  return <>
    {signedOut && (
      <section className="mb-8 bg-[#ff6ed2] px-5 py-4 text-sm text-[#460a23] sm:px-6" role="status">
        You are signed out of Masumi Learn on this device. Your course progress stays on your Sokosumi-linked account for the next sign-in.
      </section>
    )}
    {user && (
      <section className="mb-8 border border-black/[0.04] bg-white p-5 sm:flex sm:items-center sm:justify-between sm:gap-6 sm:p-6">
        <div>
          <p className="text-[13px] uppercase tracking-[0.02em] text-[#FA008C]">Signed in</p>
          <p className="mt-1 text-[20px] font-semibold leading-[28px]">Welcome back, {name}</p>
          <p className="mt-1 text-[13px] leading-[1.5] text-[#919191]">
            {progress && progress.passedQuizzes.length
              ? `${progress.passedQuizzes.length} of ${units.length} unit quizzes passed`
              : "Your progress and credentials are linked to this Sokosumi account."}
          </p>
        </div>
        <div className="mt-4 flex flex-wrap gap-2 sm:mt-0 sm:justify-end">
          <Link href="/learn/course" className="rounded-full bg-[#6400FF] px-5 py-2.5 text-[14px] font-medium tracking-[0.01em] text-white transition-colors duration-200 hover:bg-[#5200d0]">My learning</Link>
          <Link href="/learn/account" className="rounded-full border border-[#bbbbbb] bg-white px-5 py-2.5 text-[14px] font-medium tracking-[0.01em] text-black transition-colors duration-200 hover:bg-[#f5f5f5]">Account</Link>
          {next ? (
            <Link href={`/learn/course/${next.slug}`} className="rounded-full border border-[#bbbbbb] bg-white px-5 py-2.5 text-[14px] font-medium tracking-[0.01em] text-black transition-colors duration-200 hover:bg-[#f5f5f5]">Continue: {next.title}</Link>
          ) : (
            <Link href="/learn/course/assessment" className="rounded-full border border-[#bbbbbb] bg-white px-5 py-2.5 text-[14px] font-medium tracking-[0.01em] text-black transition-colors duration-200 hover:bg-[#f5f5f5]">Open assessment</Link>
          )}
        </div>
      </section>
    )}
    <section className="grid min-h-[62vh] items-end gap-10 pb-20 lg:grid-cols-[1.2fr_0.8fr]"><div><p className="text-[13px] uppercase tracking-[0.02em] text-[#FA008C]">Masumi Learn</p><h1 className="mt-5 max-w-4xl text-[40px] font-normal leading-[1.15] tracking-[-1.28px] md:text-[64px]">Become a certified Masumi developer.</h1><p className="mt-7 max-w-2xl text-[20px] leading-[28px] text-[#5b5b5b]">Free, about 65 minutes, four units. Finish with a verifiable Masumi Fundamentals certificate you can share anywhere—and optionally mint on Cardano.</p><div className="mt-8 flex flex-wrap items-center gap-4"><Link href="/learn/course" className="rounded-full bg-[#6400FF] px-6 py-2.5 text-[14px] font-medium tracking-[0.01em] text-white transition-colors duration-200 hover:bg-[#5200d0]">Start the course →</Link><Link href="/learn/library" className="text-[14px] font-medium text-[#5b5b5b] transition-colors duration-200 hover:text-[#6400FF]">Browse the knowledge base</Link></div></div><div className="bg-[#FA008C] p-8 text-white"><p className="text-sm text-white/70">Masumi Fundamentals</p><p className="mt-3 text-[40px] font-normal tracking-[-0.4px]">~65 min</p><div className="mt-12 grid grid-cols-2 gap-5 border-t border-white/25 pt-6 text-sm"><div><strong className="block text-2xl">4</strong><span className="text-white/70">units</span></div><div><strong className="block text-2xl">16</strong><span className="text-white/70">practice questions</span></div><div><strong className="block text-2xl">75%</strong><span className="text-white/70">passing score</span></div><div><strong className="block text-2xl">✓</strong><span className="text-white/70">verifiable certificate</span></div></div></div></section>
    <section className="border-t border-black/10 py-16"><div className="grid gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div className="border border-black/[0.04] bg-white p-8 sm:p-10"><div className="flex items-center justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-[#6400FF] text-xl text-white">✓</span><span className="text-[13px] uppercase tracking-[0.02em] text-[#5b5b5b]">Certificate</span></div><p className="mt-8 text-[13px] uppercase tracking-[0.02em] text-[#6400FF]">Masumi Fundamentals</p><h2 className="mt-2 text-[28px] font-normal tracking-[-0.28px]">Certified</h2><p className="mt-4 text-[13px] leading-[1.5] text-[#919191]">Issued by Masumi Network</p><div className="mt-6 grid grid-cols-2 gap-4 border-t border-black/[0.04] pt-5 text-sm"><div><span className="block text-xs text-[#919191]">Assessment</span><strong className="font-medium">Your score %</strong></div><div><span className="block text-xs text-[#919191]">Issued</span><strong className="font-medium">Your date</strong></div></div></div><div><p className="text-[13px] uppercase tracking-[0.02em] text-[#FA008C]">What you earn</p><h2 className="mt-3 text-[28px] font-normal leading-[1.2] tracking-[-0.4px] md:text-[40px]">A certificate anyone can verify.</h2><ul className="mt-6 space-y-4 text-[16px] leading-[24px] text-[#5b5b5b]"><li className="flex gap-3"><span className="text-[#6400FF]">✓</span>A shareable public verification link that always shows current validity.</li><li className="flex gap-3"><span className="text-[#6400FF]">✓</span>A downloadable certificate for your portfolio or profile.</li><li className="flex gap-3"><span className="text-[#6400FF]">✓</span>An optional on-chain Cardano mint—with no personal data on-chain, ever.</li></ul></div></div></section>
    <section className="border-t border-black/10 py-16"><p className="text-[13px] uppercase tracking-[0.02em] text-[#FA008C]">Syllabus</p><h2 className="mt-3 text-[28px] font-normal leading-[1.2] tracking-[-0.4px] md:text-[40px]">Four units, open to everyone.</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{units.map((unit) => <Link key={unit.slug} href={`/learn/course/${unit.slug}`} className="group flex flex-col border border-black/[0.04] bg-white p-6 transition-[border-color,transform] duration-300 hover:border-black/10 hover:-translate-y-1"><div className="mb-5 flex items-center justify-between"><span className="text-[11px] font-mono tracking-wide text-[#FA008C]">0{unit.number}</span><div className="h-2 w-2 rounded-full bg-[#FA008C] opacity-50" /></div><h3 className="text-[17px] font-medium leading-snug text-black">{unit.title}</h3><p className="mt-2 text-[13px] leading-[1.5] text-[#919191]">{unit.summary}</p><div className="mt-5 flex items-center justify-between border-t border-black/[0.04] pt-3"><span className="text-[14px] font-medium text-[#FA008C]">Read the lesson <span className="inline-block transition group-hover:translate-x-1">→</span></span><span className="text-xs text-[#919191]">{unit.duration}</span></div></Link>)}</div></section>
    <section className="border border-black/[0.04] bg-white p-8 sm:p-12"><p className="text-[13px] uppercase tracking-[0.02em] text-[#FA008C]">How it works</p><div className="mt-6 grid gap-6 md:grid-cols-3"><Step number={1} title="Read the four units" body="Short lessons on the agent economy, Masumi, Cardano, and trusted payments. No prerequisites, lessons open to everyone." /><Step number={2} title="Pass the quizzes and final assessment" body="Each unit ends with a short quiz; the final assessment needs 75% or higher. The server grades every attempt." /><Step number={3} title="Claim your certificate" body="Get a verifiable Masumi Fundamentals certificate, share the public verify link, and optionally mint it on Cardano." /></div></section>
    <section className="mt-8 grid gap-3 sm:grid-cols-3"><TrackedLink href="https://www.masumi.network/dev/masumi/documentation/get-started/install-masumi-node" event="learn_quickstart_start" params={{ surface: "landing" }} className="group border border-black/[0.04] bg-white p-5 transition-[border-color,transform] duration-300 hover:border-black/10 hover:-translate-y-1"><span className="block text-[11px] font-mono uppercase tracking-wide text-[#FA008C]">Ready to build?</span><strong className="mt-2 block text-[17px] font-medium leading-snug transition-colors duration-200 group-hover:text-[#6400FF]">Open the Docs quickstarts <span className="inline-block transition group-hover:translate-x-1">→</span></strong></TrackedLink><TrackedLink href="https://www.masumi.network/dev/masumi/documentation" event="learn_docs_handoff" params={{ surface: "landing", destination: "documentation" }} className="group border border-black/[0.04] bg-white p-5 transition-[border-color,transform] duration-300 hover:border-black/10 hover:-translate-y-1"><span className="block text-[11px] font-mono uppercase tracking-wide text-[#FA008C]">Need reference?</span><strong className="mt-2 block text-[17px] font-medium leading-snug transition-colors duration-200 group-hover:text-[#6400FF]">Read the documentation <span className="inline-block transition group-hover:translate-x-1">→</span></strong></TrackedLink><TrackedLink href="https://sokosumi.com" event="learn_sokosumi_handoff" params={{ surface: "landing" }} className="group border border-black/[0.04] bg-white p-5 transition-[border-color,transform] duration-300 hover:border-black/10 hover:-translate-y-1"><span className="block text-[11px] font-mono uppercase tracking-wide text-[#FA008C]">Exploring?</span><strong className="mt-2 block text-[17px] font-medium leading-snug transition-colors duration-200 group-hover:text-[#6400FF]">See live agents on Sokosumi <span className="inline-block transition group-hover:translate-x-1">→</span></strong></TrackedLink></section>
  </>;
}

function Step({ number, title, body }: { number: number; title: string; body: string }) { return <div className="border border-black/[0.04] bg-white p-6"><div className="mb-5 flex items-center justify-between"><span className="text-[11px] font-mono tracking-wide text-[#6400FF]">0{number}</span><div className="h-2 w-2 rounded-full bg-[#6400FF] opacity-50" /></div><h3 className="text-[17px] font-medium leading-snug text-black">{title}</h3><p className="mt-2 text-[13px] leading-[1.5] text-[#919191]">{body}</p></div>; }
