import Link from "next/link";
import { requireLearnUser } from "@/lib/learn-auth";
import { DeleteLearnAccountButton } from "../learner-actions";

export const metadata = { title: "Learn account" };

export default async function LearnAccountPage() {
  const user = await requireLearnUser("/learn/account");
  return <div className="mx-auto max-w-2xl"><Link href="/learn/dashboard" className="text-sm text-black/55">← My learning</Link><section className="mt-6 rounded-3xl bg-white p-7 shadow-sm sm:p-10"><p className="text-xs uppercase tracking-[0.18em] text-[#A50045]">Sokosumi-linked account</p><h1 className="mt-3 text-4xl font-medium tracking-tight">Account and privacy</h1><dl className="mt-8 space-y-5 text-sm"><div><dt className="text-black/45">Display name</dt><dd className="mt-1 font-medium">{user.displayName || "Not provided"}</dd></div><div><dt className="text-black/45">Email</dt><dd className="mt-1 font-medium">{user.email || "Not provided by Sokosumi"}</dd></div><div><dt className="text-black/45">Identity source</dt><dd className="mt-1 font-medium">Sokosumi OAuth</dd></div></dl><div className="mt-9 border-t border-black/10 pt-7"><h2 className="text-xl font-medium">Your data</h2><p className="mt-2 text-sm leading-6 text-black/55">Export your profile, course progress, attempt history, Builder proof/status, and credential records. OAuth tokens, wallet secrets, and raw answers are never included because they are not stored.</p><a href="/api/learn/account" className="mt-4 inline-block rounded-full border border-black/15 px-5 py-3 text-sm">Export my Learn data</a></div><div className="mt-9 border-t border-black/10 pt-7"><h2 className="text-xl font-medium">Disconnect and recovery</h2><p className="mt-2 text-sm leading-6 text-black/55">Logging out ends this browser session and asks Sokosumi to end the provider session before returning to Learn. Revoking the OAuth grant is a separate provider-side action. If you lose account access, support must verify recovery through Sokosumi; Learn never uses email alone to reassign progress or credentials.</p><form action="/api/learn/auth/logout" method="post"><button className="mt-4 rounded-full border border-black/15 px-5 py-3 text-sm">Log out of Learn and Sokosumi</button></form></div><div className="mt-9 border-t border-red-200 pt-7"><h2 className="text-xl font-medium text-red-800">Delete Learn account</h2><p className="mt-2 text-sm leading-6 text-black/55">This removes profile, course activity, and Builder proof and signs you out. Issued credentials are retained only as anonymous revoked records so public verification and permanent on-chain records are not misleading.</p><DeleteLearnAccountButton /></div></section></div>;
}
