import Link from "next/link";
import { getCurrentLearnUser } from "@/lib/learn-auth";
import { getCredentialsForUser, getProgress } from "@/lib/learn-db";
import { PASSING_SCORE, units } from "../course-data";
import { MintCredentialButton, RefreshMintStatusButton, TrackedConversionLink } from "../learner-actions";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";
export const metadata = { title: "Fundamentals course" };

export default async function CoursePage() {
  const user = await getCurrentLearnUser();
  if (!user) {
    return <>
      <div className="mb-10"><p className="text-[13px] uppercase tracking-[0.02em] text-[#FA008C]">Masumi Fundamentals</p><h1 className="mt-3 text-[40px] font-normal leading-[1.15] tracking-[-1.28px] md:text-[64px]">The course</h1><p className="mt-4 max-w-2xl text-[20px] leading-[28px] text-[#5b5b5b]">Four assessed units move from the agent economy to trusted payment outcomes. Lessons are open to everyone; pass the quizzes and the final assessment ({PASSING_SCORE}%) to earn a verifiable certificate.</p></div>
      <div className="mb-8 flex flex-wrap items-center justify-between gap-4 border border-black/[0.04] bg-white px-6 py-5"><p className="text-[16px] leading-[24px] text-[#5b5b5b]">Sign in to track progress and earn your certificate.</p><Link href="/learn/login?returnTo=/learn/course" className="rounded-full bg-[#6400FF] px-6 py-2.5 text-[14px] font-medium tracking-[0.01em] text-white transition-colors duration-200 hover:bg-[#5200d0]">Sign in with Sokosumi →</Link></div>
      <div className="grid gap-4 md:grid-cols-2">{units.map((unit) => <Link key={unit.slug} href={`/learn/course/${unit.slug}`} className="group border border-black/[0.04] bg-white p-6 transition-[border-color,transform] duration-300 hover:border-black/10 hover:-translate-y-1"><div className="mb-5 flex items-center justify-between"><span className="text-[11px] font-mono tracking-wide text-[#FA008C]">{String(unit.number).padStart(2, "0")}</span><div className="w-2 h-2 rounded-full bg-[#FA008C] opacity-50" /></div><h2 className="text-[17px] font-medium text-black leading-snug mb-2">{unit.title}</h2><p className="text-[13px] text-[#919191] leading-[1.5]">{unit.summary}</p><div className="border-t border-black/[0.04] pt-3 mt-5 flex items-center justify-between"><span className="text-[14px] font-medium tracking-[0.01em] text-black">Start lesson <span className="inline-block transition group-hover:translate-x-1">→</span></span><span className="text-[13px] tracking-[0.02em] text-[#919191]">{unit.duration}</span></div></Link>)}</div>
      <div className="mt-8 flex flex-col items-start justify-between gap-5 bg-[#0a0a0a] p-7 text-white sm:flex-row sm:items-center"><div><p className="text-[13px] uppercase tracking-[0.02em] text-[#f5f5f5]/70">Final assessment</p><h2 className="mt-2 text-[28px] font-normal leading-[1.2] tracking-[-0.4px]">Earn the Fundamentals certificate</h2><p className="mt-2 max-w-xl text-[16px] leading-[24px] text-[#f5f5f5]/70">Pass all unit quizzes, then score at least {PASSING_SCORE}%. Quizzes and the assessment require a signed-in account.</p></div><Link href="/learn/login?returnTo=/learn/course" className="shrink-0 rounded-full bg-[#6400FF] px-6 py-2.5 text-[14px] font-medium tracking-[0.01em] text-white transition-colors duration-200 hover:bg-[#5200d0]">Sign in to begin</Link></div>
    </>;
  }
  const progress = getProgress(user.id);
  const credentials = getCredentialsForUser(user.id);
  const credential = credentials.find((item) => item.credentialType === "fundamentals" && item.status !== "revoked" && item.status !== "superseded") ?? null;
  const builderCredential = credentials.find((item) => item.credentialType === "builder" && item.status !== "revoked" && item.status !== "superseded") ?? null;
  const next = units.find((unit) => !progress.passedQuizzes.includes(unit.slug));
  const assessmentEligible = progress.passedQuizzes.length === units.length && progress.assessmentScore == null;
  const attempts = [
    ...progress.quizAttempts.map((attempt) => ({ kind: units.find((unit) => unit.slug === attempt.unitSlug)?.title || attempt.unitSlug, ...attempt })),
    ...progress.assessmentAttempts.map((attempt) => ({ kind: "Final assessment", unitSlug: "assessment", ...attempt })),
  ].sort((a, b) => b.attemptedAt.localeCompare(a.attemptedAt)).slice(0, 8);
  const explorerUrl = credential?.explorerUrl?.startsWith("https://") ? credential.explorerUrl : null;
  return <>
    <section className="flex flex-col justify-between gap-6 border-b border-black/10 pb-10 sm:flex-row sm:items-end"><div><p className="text-[13px] uppercase tracking-[0.02em] text-[#FA008C]">Your Sokosumi-linked learning</p><h1 className="mt-3 text-[40px] font-normal leading-[1.15] tracking-[-1.28px] md:text-[64px]">Hello, {user.displayName || user.email?.split("@")[0] || "learner"}</h1><p className="mt-3 text-[16px] leading-[24px] text-[#5b5b5b]">Progress and credentials belong to this account.</p></div><Link href="/learn/account" className="rounded-full border border-[#bbbbbb] bg-white px-6 py-2.5 text-[14px] font-medium tracking-[0.01em] text-black transition-colors duration-200 hover:bg-[#f5f5f5]">Account and privacy</Link></section>
    <div className="mt-8 grid gap-5 lg:grid-cols-[1.25fr_0.75fr]">
      <section className="border border-black/[0.04] bg-white p-7"><div className="flex items-center justify-between"><h2 className="text-[20px] font-semibold leading-[28px]">Fundamentals</h2><span className="text-[13px] tracking-[0.02em] text-[#5b5b5b]">{progress.passedQuizzes.length} / {units.length} units</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-[#ebebeb]"><div className="h-full rounded-full bg-[#FA008C]" style={{ width: `${progress.passedQuizzes.length / units.length * 100}%` }} /></div><div className="mt-7 grid gap-3 sm:grid-cols-2">{units.map((unit) => <Link key={unit.slug} href={`/learn/course/${unit.slug}`} className="border border-black/[0.04] bg-white p-4 transition-[border-color,transform] duration-300 hover:border-black/10 hover:-translate-y-1"><span className="flex items-center justify-between"><span className="text-[11px] font-mono tracking-wide text-[#FA008C]">{String(unit.number).padStart(2, "0")}</span><span className="w-2 h-2 rounded-full bg-[#FA008C] opacity-50" /></span><strong className="mt-2 block text-[15px] font-medium text-black leading-snug">{unit.title}</strong><span className={`mt-2 block text-[13px] tracking-[0.02em] ${progress.passedQuizzes.includes(unit.slug) ? "text-[#FA008C]" : "text-[#5b5b5b]"}`}>{progress.passedQuizzes.includes(unit.slug) ? `Passed · ${progress.quizScores[unit.slug]}%` : progress.completedLessons.includes(unit.slug) ? "Lesson complete" : "Not started"}</span></Link>)}</div>{next ? <Link href={`/learn/course/${next.slug}`} className="mt-7 inline-block rounded-full bg-[#0a0a0a] px-6 py-2.5 text-[14px] font-medium tracking-[0.01em] text-white transition-colors duration-200 hover:bg-black">Continue: {next.title} →</Link> : <Link href="/learn/course/assessment" className="mt-7 inline-block rounded-full bg-[#0a0a0a] px-6 py-2.5 text-[14px] font-medium tracking-[0.01em] text-white transition-colors duration-200 hover:bg-black">Open assessment →</Link>}</section>
      <section className="bg-[#0a0a0a] p-7 text-white"><p className="text-[13px] uppercase tracking-[0.02em] text-[#f5f5f5]/70">Credential</p>{credential ? <><h2 className="mt-3 text-[28px] font-normal leading-[1.2] tracking-[-0.4px]">Masumi Fundamentals</h2><p className="mt-3 text-[14px] leading-[24px] text-[#f5f5f5]/70">Issued {new Date(credential.issuedAt).toLocaleDateString()} · {credential.score}%</p><p className="mt-6 rounded-full bg-white/10 px-3 py-2 text-center text-[13px] uppercase tracking-[0.02em]">{credential.status.replaceAll("_", " ")}</p>{credential.status === "mint_failed" && <p role="alert" className="mt-3 text-[14px] leading-[24px] text-[#ff6400]">The off-chain credential is safe. You can retry or reconcile the on-chain request.</p>}{credential.status === "revoked" && <p className="mt-3 text-[14px] leading-[24px] text-[#ffcac5]">This credential has been revoked and cannot be minted.</p>}{credential.status === "superseded" && <p className="mt-3 text-[14px] leading-[24px] text-[#ff6400]">A newer course-version credential replaced this one.</p>}<div className="mt-5 space-y-3"><Link href={`/learn/verify/${credential.id}`} className="block rounded-full bg-white px-6 py-2.5 text-center text-[14px] font-medium tracking-[0.01em] text-black transition-colors duration-200 hover:bg-[#f5f5f5]">View public certificate</Link>{explorerUrl && <a href={explorerUrl} className="block rounded-full border border-white/25 px-6 py-2.5 text-center text-[14px] font-medium tracking-[0.01em] transition-colors duration-200 hover:bg-white/10">View transaction ↗</a>}{(credential.status === "ready_to_mint" || credential.status === "mint_failed") && <MintCredentialButton />}{(credential.status === "minting" || credential.status === "mint_failed") && <RefreshMintStatusButton />}</div><p className="mt-5 text-[13px] leading-5 tracking-[0.02em] text-[#f5f5f5]/70">Minting is optional. Chain records are permanent and contain only the credential ID/hash, course/version, and issuer—not your name, email, OAuth data, or answers.</p></> : <><h2 className="mt-3 text-[28px] font-normal leading-[1.2] tracking-[-0.4px]">{assessmentEligible ? "Assessment ready" : progress.completedLessons.length ? "In progress" : "Not started"}</h2><p className="mt-3 text-[14px] leading-[24px] text-[#f5f5f5]/70">{assessmentEligible ? "You passed every unit quiz. Complete the final assessment to earn the credential." : "Pass every unit quiz and the final assessment. Eligibility is checked by the server."}</p>{assessmentEligible && <Link href="/learn/course/assessment" className="mt-5 block rounded-full bg-[#6400FF] px-6 py-2.5 text-center text-[14px] font-medium tracking-[0.01em] text-white transition-colors duration-200 hover:bg-[#5200d0]">Take final assessment</Link>}</>}</section>
    </div>
    {builderCredential && <section className="mt-5 border border-black/[0.04] bg-white p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-[13px] uppercase tracking-[0.02em] text-[#FA008C]">Additional credential</p><h2 className="mt-2 text-[20px] font-semibold leading-[28px]">Masumi Builder</h2><p className="mt-2 text-[14px] leading-[24px] text-[#5b5b5b]">Issued {new Date(builderCredential.issuedAt).toLocaleDateString()} · {builderCredential.score}% · {builderCredential.status.replaceAll("_", " ")}</p></div><Link href={`/learn/verify/${builderCredential.id}`} className="rounded-full border border-[#bbbbbb] bg-white px-6 py-2.5 text-[14px] font-medium tracking-[0.01em] text-black transition-colors duration-200 hover:bg-[#f5f5f5]">View Builder certificate</Link></div></section>}
    <section className="mt-5 border border-black/[0.04] bg-white p-7"><div className="flex items-end justify-between gap-4"><div><p className="text-[13px] uppercase tracking-[0.02em] text-[#FA008C]">Attempt history</p><h2 className="mt-2 text-[20px] font-semibold leading-[28px]">Recent knowledge checks</h2></div><span className="text-[13px] tracking-[0.02em] text-[#5b5b5b]">No answers retained</span></div>{attempts.length ? <ul className="mt-5 divide-y divide-black/10">{attempts.map((attempt, index) => <li key={`${attempt.unitSlug}-${attempt.attemptedAt}-${index}`} className="flex items-center justify-between gap-4 py-3 text-[14px]"><div><strong className="font-medium">{attempt.kind}</strong><span className="ml-2 text-[#5b5b5b]">{new Date(attempt.attemptedAt).toLocaleString()}</span></div><span className={attempt.passed ? "text-[#FA008C]" : "text-[#5b5b5b]"}>{attempt.score}% · {attempt.passed ? "Passed" : "Review"}</span></li>)}</ul> : <p className="mt-5 bg-black/[0.03] p-5 text-[14px] leading-[24px] text-[#5b5b5b]">Your quiz and assessment attempts will appear here after the first submission.</p>}</section>
    {credential && <section className="mt-5 grid gap-3 sm:grid-cols-2"><TrackedConversionLink href="https://www.masumi.network/dev/masumi/documentation/get-started/install-masumi-node" event="learn_docs_conversion" params={{ has_builder_credential: builderCredential ? 1 : 0 }}>Start your first Masumi integration →</TrackedConversionLink><TrackedConversionLink href="https://www.masumi.network/dev/masumi/documentation/how-to-guides/list-agent-on-sokosumi" event="learn_publish_conversion" params={{ has_builder_credential: builderCredential ? 1 : 0 }}>Prepare a service for Sokosumi →</TrackedConversionLink></section>}
  </>;
}
