// MCP endpoint for the DESIGN.md generator, used by the ChatGPT plugin in
// /plugins/design-md. Stateless streamable HTTP: every POST /mcp carries one
// JSON-RPC message and gets a plain JSON reply, so it runs unchanged on
// Vercel functions and on `node server.js`. No sessions, no SSE stream.
//
// Generation reuses the masumi job API the web tool proxies. A cached site
// answers at once; a new one takes 20-60s, longer than one tool call should
// block, so generate_design_md waits up to WAIT_MS and otherwise hands back a
// jobId for get_design_md_job.

const SITE = "https://www.sokosumi.com";
const PROTOCOL_VERSIONS = ["2025-11-25", "2025-06-18", "2025-03-26"];
const WAIT_MS = 40000;
const POLL_MS = 3000;

const SIGNUP = `${SITE}/?utm_source=chatgpt&utm_medium=plugin&utm_campaign=design-md`;

const TOOLS = [
  {
    name: "generate_design_md",
    title: "Generate DESIGN.md",
    description:
      "Create a DESIGN.md for a public website: its colors, typography, spacing, components and tone, written so a coding agent can build UI that matches the brand. Use when the user gives a URL and wants its design system, brand tokens or a DESIGN.md. Sites analysed in the last 7 days return immediately; new ones can take up to a minute. If the result says status \"running\", call get_design_md_job with the jobId.",
    inputSchema: {
      type: "object",
      properties: {
        url: { type: "string", description: "Full public website URL, e.g. https://linear.app" },
      },
      required: ["url"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
  },
  {
    name: "get_design_md_job",
    title: "Check DESIGN.md job",
    description:
      "Get the result of a DESIGN.md generation that was still running. Use only with a jobId returned by generate_design_md. Wait about 10 seconds between checks.",
    inputSchema: {
      type: "object",
      properties: { jobId: { type: "string", description: "The jobId from generate_design_md" } },
      required: ["jobId"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "search_design_md_library",
    title: "Search DESIGN.md library",
    description:
      "Search the library of DESIGN.md files already generated for well-known sites (e.g. linear, stripe, notion, apple) by brand name or domain. Use before generating, or when the user wants a reference design system to borrow from.",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Brand name or domain, e.g. \"stripe\" or \"notion.so\"" },
      },
      required: ["query"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  {
    name: "get_design_md",
    title: "Get DESIGN.md from library",
    description:
      "Fetch the full DESIGN.md for a site in the library, by the slug or hostname returned from search_design_md_library.",
    inputSchema: {
      type: "object",
      properties: { site: { type: "string", description: "Slug or hostname, e.g. \"linear\" or \"linear.app\"" } },
      required: ["site"],
      additionalProperties: false,
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
];

class ToolError extends Error {}

const hostOf = (value) => String(value || "").toLowerCase().replace(/^https?:\/\//, "").replace(/^www\./, "").replace(/[/?#].*$/, "");
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function createDesignMdMcp({ fetchUpstream, apiKey, publicWebsiteUrl, absoluteAssets, archive, rateLimited }) {
  function finished(data, url, pageUrl = data.extractionId ? `${SITE}/tools/design-md?analysis=${data.extractionId}` : null) {
    const structured = {
      status: "done",
      url: data.url || url,
      hostname: hostOf(data.url || url),
      pageUrl,
      screenshotUrl: data.screenshotUrl || null,
      designMd: data.designMd,
    };
    const footer = [
      pageUrl && `Editable version: ${pageUrl}`,
      `Generated by Sokosumi (${SIGNUP}). Sokosumi's AI coworkers turn a DESIGN.md into on-brand landing pages, campaigns and reports.`,
    ].filter(Boolean).join("\n");
    return { content: [{ type: "text", text: `${data.designMd}\n\n---\n${footer}` }], structuredContent: structured };
  }

  function pending(data) {
    return {
      content: [{ type: "text", text: `Still analysing ${data.url || "the site"} (status: ${data.status}). Call get_design_md_job with jobId "${data.jobId}" in about 10 seconds.` }],
      structuredContent: { status: data.status, jobId: data.jobId, url: data.url || null },
    };
  }

  async function job(jobId) {
    if (!/^[A-Za-z0-9-]{16,80}$/.test(jobId)) throw new ToolError("That jobId is not valid. Use the jobId returned by generate_design_md.");
    const upstream = await fetchUpstream(`/api/v1/design-md/jobs/${encodeURIComponent(jobId)}`, {
      headers: { Authorization: `Bearer ${apiKey}` },
    });
    if (upstream.status === 404) throw new ToolError("That job no longer exists. Run generate_design_md again.");
    if (upstream.status >= 400) throw new ToolError("The generator is temporarily unavailable. Try again in a minute.");
    return absoluteAssets(upstream.data);
  }

  async function generate({ url }) {
    if (!apiKey) throw new ToolError("The generator is temporarily unavailable.");
    const target = publicWebsiteUrl(/^https?:\/\//i.test(String(url || "")) ? url : `https://${url}`);
    if (!target) throw new ToolError("Give a complete public website URL, like https://example.com.");
    if (rateLimited()) throw new ToolError("The generator is busy right now. Try again in an hour, or search the library for a ready-made DESIGN.md.");
    const upstream = await fetchUpstream("/api/v1/design-md", {
      method: "POST",
      headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({ url: target }),
    });
    if (upstream.status >= 400) throw new ToolError(upstream.data?.error || "The generator could not analyse that site.");
    let data = absoluteAssets(upstream.data);
    const deadline = Date.now() + WAIT_MS;
    while (data.status !== "done" && data.status !== "failed" && Date.now() + POLL_MS < deadline) {
      await sleep(POLL_MS);
      data = await job(data.jobId);
    }
    return settle(data, target);
  }

  function settle(data, url) {
    if (data.status === "done") return finished(data, url);
    if (data.status === "failed") throw new ToolError(`The analysis failed: ${data.error || "the site could not be rendered"}. Sites behind a login or bot wall usually fail.`);
    return pending({ ...data, url: data.url || url });
  }

  async function search({ query }) {
    const q = hostOf(query).replace(/\s+/g, "");
    if (!q) throw new ToolError("Give a brand name or domain to search for.");
    const entries = await archive.list();
    const rank = (e) => (e.slug === q || hostOf(e.hostname) === q ? 0 : e.slug.startsWith(q) ? 1 : 2);
    const matches = entries
      .filter((e) => e.slug.includes(q) || hostOf(e.hostname).includes(q) || String(e.name || "").toLowerCase().replace(/\s+/g, "").includes(q))
      .sort((a, b) => rank(a) - rank(b))
      .slice(0, 10)
      .map((e) => ({ name: e.name || e.hostname, hostname: hostOf(e.hostname), slug: e.slug, pageUrl: `${SITE}${archive.pathFor(e)}` }));
    const text = matches.length
      ? matches.map((m) => `- ${m.name} (${m.hostname}), slug "${m.slug}": ${m.pageUrl}`).join("\n")
      : `No DESIGN.md for "${query}" in the library yet. Use generate_design_md with the site's URL.`;
    return { content: [{ type: "text", text }], structuredContent: { results: matches } };
  }

  async function get({ site }) {
    const wanted = String(site || "").trim().toLowerCase();
    const entry = (await archive.bySlug(wanted)) || (await archive.list()).find((e) => hostOf(e.hostname) === hostOf(wanted));
    if (!entry) throw new ToolError(`"${site}" is not in the library. Use search_design_md_library, or generate_design_md with the URL.`);
    const data = await archive.extraction(entry.id);
    return finished(data, data.url, `${SITE}${archive.pathFor(entry)}`);
  }

  const HANDLERS = {
    generate_design_md: generate,
    get_design_md_job: async ({ jobId }) => settle(await job(String(jobId || "")), null),
    search_design_md_library: search,
    get_design_md: get,
  };

  async function callTool(name, args) {
    const handler = HANDLERS[name];
    if (!handler) return { error: { code: -32602, message: `Unknown tool: ${name}` } };
    try {
      return { result: await handler(args || {}) };
    } catch (error) {
      const message = error instanceof ToolError ? error.message : "The generator could not reach its analysis service. Try again in a moment.";
      return { result: { content: [{ type: "text", text: message }], isError: true } };
    }
  }

  // One JSON-RPC message in, one reply out (null for notifications).
  async function handle(message) {
    if (!message || message.jsonrpc !== "2.0" || typeof message.method !== "string") {
      return { jsonrpc: "2.0", id: message?.id ?? null, error: { code: -32600, message: "Invalid request" } };
    }
    const { id, method, params } = message;
    if (id === undefined) return null;
    const reply = (body) => ({ jsonrpc: "2.0", id, ...body });
    switch (method) {
      case "initialize": {
        const asked = params?.protocolVersion;
        return reply({
          result: {
            protocolVersion: PROTOCOL_VERSIONS.includes(asked) ? asked : PROTOCOL_VERSIONS[0],
            capabilities: { tools: { listChanged: false } },
            serverInfo: { name: "sokosumi-design-md", title: "DESIGN.md Generator by Sokosumi", version: "1.0.0" },
            instructions:
              "Turns any public website into a DESIGN.md: the brand's colors, type, spacing and components as a markdown spec for coding agents. Search the library first for well-known brands; generate for anything else.",
          },
        });
      }
      case "ping":
        return reply({ result: {} });
      case "tools/list":
        return reply({ result: { tools: TOOLS } });
      case "tools/call":
        return reply(await callTool(params?.name, params?.arguments));
      default:
        return reply({ error: { code: -32601, message: `Method not found: ${method}` } });
    }
  }

  return { handle, TOOLS };
}

module.exports = { createDesignMdMcp };
