import Link from "next/link";
import { publicCredential } from "@/lib/learn-credentials";
import { CopyCertificateLinkButton } from "../../learner-actions";

export default async function VerifyCredentialPage({ params }: { params: Promise<{ id: string }> }) {
  const credential = publicCredential((await params).id);
  if (!credential) return <div className="mx-auto max-w-xl border border-black/[0.04] bg-white p-10 text-center"><p className="text-[13px] uppercase tracking-[0.02em] text-[#fa140a]">Not found</p><h1 className="mt-3 text-[28px] font-normal tracking-[-0.4px] leading-[1.2] md:text-[40px]">Unknown credential</h1><p className="mt-3 text-[16px] leading-[24px] text-[#5b5b5b]">No Masumi Learn credential exists with this identifier.</p></div>;
  const valid = credential.status === "ready_to_mint" || credential.status === "minting" || credential.status === "minted" || credential.status === "mint_failed";
  const explorerUrl = credential.explorerUrl?.startsWith("https://") ? credential.explorerUrl : null;
  return <div className="mx-auto max-w-3xl"><section className="border border-black/[0.04] bg-white p-8 text-center sm:p-14"><div className={`mx-auto flex h-20 w-20 items-center justify-center rounded-full text-3xl ${valid ? "bg-[#ff6ed2] text-[#460a23]" : "bg-[#ffcac5] text-[#5a0a00]"}`}>{valid ? "✓" : "!"}</div><p className="mt-7 text-[13px] uppercase tracking-[0.02em] text-[#FA008C]">Masumi Learn credential</p><h1 className="mt-3 text-[40px] font-normal tracking-[-1.28px] leading-[1.15] md:text-[64px]">{credential.course}</h1><p className={`mx-auto mt-4 inline-block rounded-full px-3 py-1 text-[13px] ${valid ? "bg-[#ff6ed2] text-[#460a23]" : "bg-[#ffcac5] text-[#5a0a00]"}`}>{valid ? "Valid credential" : credential.status.replaceAll("_", " ")}</p><dl className="mx-auto mt-8 grid max-w-xl gap-4 border-t border-black/10 pt-7 text-left text-[14px] sm:grid-cols-2"><Field label="Credential ID" value={credential.credentialId} /><Field label="Credential level" value={credential.credentialType} /><Field label="Course version" value={credential.courseVersion} /><Field label="Issued" value={new Date(credential.issuedAt).toLocaleDateString()} /><Field label="Assessment" value={`${credential.score}%`} /><Field label="On-chain status" value={credential.status.replaceAll("_", " ")} /><Field label="Issuer" value={credential.issuer} />{credential.network && <Field label="Network" value={credential.network} />}{credential.txHash && <Field label="Transaction" value={credential.txHash} />}{credential.assetId && <Field label="Asset" value={credential.assetId} />}{credential.supersededBy && <Field label="Superseded by" value={credential.supersededBy} />}</dl><div className="mt-8 flex flex-wrap justify-center gap-3"><a href={`/api/learn/verify/${credential.credentialId}/certificate`} className="rounded-full border border-[#bbbbbb] bg-white px-6 py-2.5 text-[14px] font-medium tracking-[0.01em] text-black transition-colors duration-200 hover:bg-[#f5f5f5]">Download certificate</a><CopyCertificateLinkButton path={`/learn/verify/${credential.credentialId}`} />{explorerUrl && <a href={explorerUrl} className="text-[14px] font-medium tracking-[0.01em] transition-colors duration-200 hover:text-[#6400FF]">View on explorer ↗</a>}</div></section><p className="mt-5 text-center text-[13px] tracking-[0.02em] text-[#5b5b5b]">This public view intentionally contains no OAuth token, email, account identifier, or private course activity. On-chain records cannot be deleted; current validity is always checked here.</p><div className="mt-5 text-center"><Link href="/learn" className="text-[14px] font-medium tracking-[0.01em] transition-colors duration-200 hover:text-[#6400FF]">Explore Masumi Learn →</Link></div></div>;
}

function Field({ label, value }: { label: string; value: string }) { return <div><dt className="text-[13px] uppercase tracking-[0.02em] text-[#5b5b5b]">{label}</dt><dd className="mt-1 break-all font-medium">{value}</dd></div>; }
