import Link from "next/link";
import { publicCredential } from "@/lib/learn-credentials";
import { CopyCertificateLinkButton } from "../../learner-actions";

export default async function VerifyCredentialPage({ params }: { params: Promise<{ id: string }> }) {
  const credential = publicCredential((await params).id);
  if (!credential) return <div className="mx-auto max-w-xl rounded-3xl bg-white p-10 text-center"><p className="text-xs uppercase tracking-widest text-red-700">Not found</p><h1 className="mt-3 text-3xl font-medium">Unknown credential</h1><p className="mt-3 text-black/55">No Masumi Learn credential exists with this identifier.</p></div>;
  const valid = credential.status === "ready_to_mint" || credential.status === "minting" || credential.status === "minted" || credential.status === "mint_failed";
  const explorerUrl = credential.explorerUrl?.startsWith("https://") ? credential.explorerUrl : null;
  return <div className="mx-auto max-w-3xl"><section className="rounded-[2.5rem] bg-white p-8 text-center shadow-sm sm:p-14"><div className={`mx-auto flex h-20 w-20 items-center justify-center rounded-full text-3xl text-white ${valid ? "bg-emerald-600" : "bg-red-600"}`}>{valid ? "✓" : "!"}</div><p className="mt-7 text-xs uppercase tracking-[0.2em] text-[#A50045]">Masumi Learn credential</p><h1 className="mt-3 text-5xl font-medium tracking-tight">{credential.course}</h1><p className="mt-3 text-lg text-black/55">{valid ? "Valid credential" : credential.status.replaceAll("_", " ")}</p><dl className="mx-auto mt-8 grid max-w-xl gap-4 border-t border-black/10 pt-7 text-left text-sm sm:grid-cols-2"><Field label="Credential ID" value={credential.credentialId} /><Field label="Credential level" value={credential.credentialType} /><Field label="Course version" value={credential.courseVersion} /><Field label="Issued" value={new Date(credential.issuedAt).toLocaleDateString()} /><Field label="Assessment" value={`${credential.score}%`} /><Field label="On-chain status" value={credential.status.replaceAll("_", " ")} /><Field label="Issuer" value={credential.issuer} />{credential.network && <Field label="Network" value={credential.network} />}{credential.txHash && <Field label="Transaction" value={credential.txHash} />}{credential.assetId && <Field label="Asset" value={credential.assetId} />}{credential.supersededBy && <Field label="Superseded by" value={credential.supersededBy} />}</dl><div className="mt-8 flex flex-wrap justify-center gap-3"><a href={`/api/learn/verify/${credential.credentialId}/certificate`} className="rounded-full bg-black px-5 py-3 text-sm text-white">Download certificate</a><CopyCertificateLinkButton path={`/learn/verify/${credential.credentialId}`} />{explorerUrl && <a href={explorerUrl} className="rounded-full border border-black/15 px-5 py-3 text-sm">View on explorer ↗</a>}</div></section><p className="mt-5 text-center text-xs text-black/45">This public view intentionally contains no OAuth token, email, account identifier, or private course activity. On-chain records cannot be deleted; current validity is always checked here.</p><div className="mt-5 text-center"><Link href="/learn" className="text-sm">Explore Masumi Learn →</Link></div></div>;
}

function Field({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs uppercase tracking-wider text-black/40">{label}</dt><dd className="mt-1 break-all font-medium">{value}</dd></div>; }
