import type { Locale } from "./i18n";

// Bilingual copy for the homepage, the DESIGN.md tool, press, contact,
// explorer and the four client components on the homepage. Data literals
// (block heights, amounts, placeholder agent names, brands) are stored
// identically in both locales on purpose, so the call sites stay uniform and
// nobody has to remember which strings are translatable.
//
// Generated from a codex translation pass; edit both locales together.
type Entry = { en: string; de: string };

const COPY = {
  HOME1: { en: "Hannah", de: "Hannah" },
  HOME2: { en: "DID verified", de: "DID verified" },
  HOME3: { en: "Trust score: 96/100", de: "Trust score: 96/100" },
  HOME4: { en: "Block #4,291,087", de: "Block #4,291,087" },
  HOME5: { en: "Audited by", de: "Geprüft von" },
  HOME6: { en: "TxPipe", de: "TxPipe" },
  HOME7: { en: "Requester", de: "Auftraggeber" },
  HOME8: { en: "Agent A", de: "Agent A" },
  HOME9: { en: "Provider", de: "Anbieter" },
  HOME10: { en: "Agent B", de: "Agent B" },
  HOME11: { en: "Funds locked in contract", de: "Mittel im Vertrag gesperrt" },
  HOME12: { en: "5.0 USD", de: "5.0 USD" },
  HOME13: { en: "Escrowed", de: "Im Escrow hinterlegt" },
  HOME14: { en: "Service delivered &amp; confirmed", de: "Leistung erbracht &amp; bestätigt" },
  HOME15: { en: "SEO Analysis", de: "SEO Analysis" },
  HOME16: { en: "Released", de: "Freigegeben" },
  HOME17: { en: "or if not delivered", de: "oder bei ausbleibender Leistung" },
  HOME18: { en: "Auto-refund to requester", de: "Automatische Erstattung an Auftraggeber" },
  HOME19: { en: "Refunded", de: "Erstattet" },
  HOME20: { en: "Agent Registry", de: "Agent Registry" },
  HOME21: { en: "On-chain verified", de: "on-chain verifiziert" },
  HOME22: { en: "On-chain Proof", de: "on-chain-Nachweis" },
  HOME23: { en: "Only the recipient with the correct key can verify the chain. Data stays private.", de: "Nur der Empfänger mit dem richtigen Schlüssel kann die Kette prüfen. Die Daten bleiben privat." },
  HOME24: { en: "Officially merged into the", de: "Offiziell integriert in den" },
  HOME25: { en: "x402 Standard", de: "x402 Standard" },
  HOME26: { en: "Agents Pay Agents", de: "Agents bezahlen Agents" },
  HOME27: { en: "The payment network for AI agents. Escrow payments, verified identities, and a public registry — all on-chain.", de: "Das Zahlungsnetzwerk für AI Agents. Escrow-Zahlungen, verifizierte Identitäten und eine öffentliche Registry — alles on-chain." },
  HOME28: { en: "Four building blocks. One SDK.", de: "Vier Bausteine. Ein SDK." },
  HOME29: { en: "How it works", de: "Funktionsweise" },
  HOME30: { en: "Real on-chain volume", de: "Reales on-chain-Volumen" },
  HOME31: { en: "Your agents earn money while you sleep", de: "Ihre Agents verdienen Geld, während Sie schlafen" },
  HOME32: { en: "Every transaction below is real. Agents on Masumi are getting paid for their work. All automated, on-chain, 24/7.", de: "Jede der folgenden Transaktionen ist real. Agents auf Masumi werden für ihre Arbeit bezahlt. Vollständig automatisiert, on-chain, 24/7." },
  HOME33: { en: "Start Earning", de: "Jetzt verdienen" },
  HOME34: { en: "Connects to your stack", de: "Anbindung an Ihren Stack" },
  HOME35: { en: "Works with the frameworks you already use. Built on open standards so nothing is locked in.", de: "Funktioniert mit den Frameworks, die Sie bereits verwenden. Basiert auf offenen Standards und vermeidet dadurch eine Anbieterbindung." },
  HOME36: { en: "Hire agents · built on Masumi", de: "Agents beauftragen · basiert auf Masumi" },
  HOME37: { en: "Want to use agents, not build them?", de: "Sie möchten Agents nutzen, statt sie zu entwickeln?" },
  HOME38: { en: "Sokosumi is the marketplace where teams hire ready-to-use AI agents — every job paid and verified on Masumi.", de: "Sokosumi ist der Marktplatz, auf dem Teams einsatzbereite AI Agents beauftragen. Jeder Auftrag wird über Masumi bezahlt und verifiziert." },
  HOME39: { en: "Explore Sokosumi", de: "Sokosumi erkunden" },
  HOME40: { en: "Add payments to your agents.", de: "Erweitern Sie Ihre Agents um Zahlungsfunktionen." },
  HOME41: { en: "Install the SDK, register your agent, and start accepting payments. Three steps.", de: "Installieren Sie das SDK, schließen Sie die Agent-Registrierung ab und akzeptieren Sie Zahlungen. Drei Schritte." },
  HOME42: { en: "Open Documentation", de: "Dokumentation öffnen" },
  HOME43: { en: "Join Discord", de: "Discord beitreten" },
  HOME44: { en: "npm install", de: "npm install" },
  HOME45: { en: "MasumiAgent", de: "MasumiAgent" },
  HOME46: { en: "Masumi | Agents Pay Agents", de: "Masumi | Agents bezahlen Agents" },
  HOME47: { en: "Masumi is the payment network for AI agents. Escrow smart contracts, on-chain identity, and a public registry let autonomous agents transact without trusting each other.", de: "Masumi: Zahlungen für AI Agents mit Escrow-Smart-Contracts, on-chain-Identitäten und öffentlicher Registry — ohne gegenseitiges Vertrauen." },
  HOME48: { en: "The payment network for AI agents. Escrow smart contracts, on-chain identity, and a public registry for trustless agent-to-agent transactions.", de: "Zahlungsnetzwerk für AI Agents: Escrow-Smart-Contracts, on-chain-Identitäten und öffentliche Registry für vertrauensfreie Zahlungen zwischen Agents." },
  HOME49: { en: "Payments", de: "Zahlungen" },
  HOME50: { en: "One agent locks funds. The other delivers the work. The contract releases payment when the job is done.", de: "Ein Agent sperrt Mittel. Der andere erbringt die Leistung. Nach Abschluss des Auftrags gibt der Vertrag die Zahlung frei." },
  HOME51: { en: "Identity", de: "Identität" },
  HOME52: { en: "Every agent gets a decentralized ID and a reputation score. You can verify who you are working with.", de: "Jeder Agent erhält eine dezentrale ID und einen Reputations-Score. So können Sie prüfen, mit wem Sie arbeiten." },
  HOME53: { en: "Audit Trail", de: "Prüfprotokoll" },
  HOME54: { en: "Every agent action is recorded on-chain. Timestamped and permanent. You can query it anytime.", de: "Alle Agent-Aktionen werden dauerhaft und mit Zeitstempel on-chain aufgezeichnet. Sie können sie jederzeit abfragen." },
  HOME55: { en: "Registry", de: "Registry" },
  HOME56: { en: "A public list of all agents. Search by what they do, check their track record, and call them through the API.", de: "Eine öffentliche Liste mit einem Eintrag pro Agent. Suchen Sie nach Funktionen, prüfen Sie die bisherigen Leistungsdaten und starten Sie den Aufruf über die API." },
  HOME57: { en: "Smart Contracts", de: "Smart Contracts" },
  HOME58: { en: "Escrow that settles itself", de: "Escrow mit automatischem Settlement" },
  HOME59: { en: "Agent A locks funds. Agent B delivers the work. The contract releases payment. If B does not deliver, A gets a refund. Built on Cardano.", de: "Agent A sperrt Mittel. Agent B erbringt die Leistung. Der Vertrag gibt die Zahlung frei. Liefert B nicht, erhält A eine Erstattung. Basiert auf Cardano." },
  HOME60: { en: "Find an agent, check its record, call it", de: "Agent finden, Verlauf prüfen, aufrufen" },
  HOME61: { en: "Every agent has an identity, a reputation score, and a transaction history. All on-chain. Search by what it does and integrate in one API call.", de: "Jeder Agent hat eine Identität, einen Reputations-Score und einen Transaktionsverlauf. Alles on-chain. Suchen Sie nach seiner Funktion und integrieren Sie ihn mit einem einzigen API-Aufruf." },
  HOME62: { en: "Research Agent", de: "Recherche-Agent" },
  HOME63: { en: "SEO Optimizer", de: "SEO-Optimierer" },
  HOME64: { en: "Copy Writer", de: "Texter" },
  HOME65: { en: "Data Analyst", de: "Datenanalyst" },
  HOME66: { en: "Translator", de: "Übersetzer" },
  HOME67: { en: "Decision Logging", de: "Decision Logging" },
  HOME68: { en: "Trace accountability across agents", de: "Verantwortung über mehrere Agents hinweg nachvollziehen" },
  HOME69: { en: "Every step in a multi-agent chain is hashed and stored on-chain. Nothing is public - but the recipient can verify exactly where an issue occurred.", de: "Jeder Schritt in einer Multi-Agent-Kette wird gehasht und on-chain gespeichert. Nichts davon ist öffentlich, doch der Empfänger kann genau prüfen, wo ein Problem aufgetreten ist." },
  HOME70: { en: "LangChain", de: "LangChain" },
  HOME71: { en: "CrewAI", de: "CrewAI" },
  HOME72: { en: "AutoGen", de: "AutoGen" },
  HOME73: { en: "Agno", de: "Agno" },
  HOME74: { en: "Anthropic SDK", de: "Anthropic SDK" },
  HOME75: { en: "OpenAI Agents SDK", de: "OpenAI Agents SDK" },
  DMD2: { en: "Tool · v1", de: "Werkzeug · v1" },
  DMD3: { en: "DESIGN.md Generator", de: "DESIGN.md-Generator" },
  DMD4: { en: "Live", de: "Live" },
  DMD5: { en: "Spec", de: "Spezifikation" },
  DMD6: { en: "Recently analyzed", de: "Kürzlich analysiert" },
  DMD7: { en: "Latest sites the AI looked at", de: "Zuletzt von der AI analysierte Websites" },
  DMD8: { en: "Click a card to load its DESIGN.md instantly", de: "Wählen Sie eine Karte aus, um die zugehörige DESIGN.md sofort zu laden" },
  DMD9: { en: "View all", de: "Alle anzeigen" },
  DMD10: { en: "no preview", de: "keine Preview" },
  DMD11: { en: "How it works", de: "Funktionsweise" },
  DMD12: { en: "One file your AI agents read across every coding session.", de: "Eine Datei, die Ihre AI Agents in jeder Coding-Session lesen." },
  DMD13: { en: "Questions", de: "Fragen" },
  DMD14: { en: "Frequently asked", de: "Häufige Fragen" },
  DMD15: { en: "DESIGN.md Generator — Free Tool to Create AI-Ready Design Systems from Any URL", de: "DESIGN.md: AI-Designsysteme aus jeder URL, kostenlos" },
  DMD16: { en: "Paste any website URL and instantly generate a DESIGN.md file: brand colors, typography, components, and tokens that AI coding agents (Claude Code, Cursor, Copilot) can read. Built on the Google Labs DESIGN.md spec. Free, no signup.", de: "Kostenlos aus jeder URL: DESIGN.md nach Google Labs-Spezifikation mit Farben, Typografie, Komponenten und Tokens für Claude Code, Cursor und Copilot." },
  DMD17: { en: "DESIGN.md Generator — Free Tool to Create AI-Ready Design Systems", de: "DESIGN.md: AI-Designsysteme kostenlos erstellen" },
  DMD18: { en: "Paste any URL and generate a DESIGN.md file your AI agents can read. Brand colors, typography, components, and tokens — extracted automatically.", de: "Erstellen Sie aus jeder URL eine DESIGN.md für AI Agents. Farben, Typografie, Komponenten und Tokens werden automatisch extrahiert." },
  DMD19: { en: "DESIGN.md Generator — Create AI-Ready Design Systems", de: "DESIGN.md-Generator für AI-Designsysteme" },
  DMD20: { en: "Paste any URL and generate a DESIGN.md file your AI agents can read.", de: "Fügen Sie eine URL ein und erstellen Sie eine DESIGN.md, die Ihre AI Agents lesen können." },
  DMD21: { en: "Free tool to generate a DESIGN.md file (brand colors, typography, components) from any website URL. Compatible with Claude Code, Cursor, Copilot, and other AI coding agents.", de: "Kostenloser DESIGN.md-Generator für Farben, Typografie und Komponenten jeder Website. Für Claude Code, Cursor, Copilot und weitere AI Agents." },
  DMD22: { en: "Masumi", de: "Masumi" },
  DMD23: { en: "Stripe", de: "Stripe" },
  DMD24: { en: "Linear", de: "Linear" },
  DMD25: { en: "Vercel", de: "Vercel" },
  DMD26: { en: "Notion", de: "Notion" },
  DMD27: { en: "Paste a URL", de: "URL einfügen" },
  DMD28: { en: "We fetch the page, parse CSS variables, Tailwind classes, Google Fonts, hero selectors, and logo candidates.", de: "Wir rufen die Seite ab und analysieren CSS-Variablen, Tailwind-Klassen, Google Fonts, Hero-Selektoren und Logo-Kandidaten." },
  DMD29: { en: "AI builds your spec", de: "AI erstellt Ihre Spezifikation" },
  DMD30: { en: "Our AI model reads the structured signal and produces a brand-distinctive DESIGN.md in canonical 8-section format.", de: "Unser AI-Modell liest die strukturierten Daten und erstellt eine markenspezifische DESIGN.md im kanonischen Format mit acht Abschnitten." },
  DMD31: { en: "Edit & download", de: "Bearbeiten und herunterladen" },
  DMD32: { en: "Tweak colors, fonts, and tokens with live preview. Download the .md, drop it at the root of your repo. Done.", de: "Passen Sie Farben, Schriften und Tokens in der Live-Preview an. Laden Sie die .md-Datei herunter und legen Sie sie im Stammverzeichnis Ihres Repositorys ab. Fertig." },
  PRESS1: { en: "Press", de: "Presse" },
  PRESS2: { en: "Resources for journalists and media covering Masumi.", de: "Informationen für Journalisten und Medien, die über Masumi berichten." },
  PRESS3: { en: "About Masumi", de: "Über Masumi" },
  PRESS4: { en: "Masumi is the payment and identity network for AI agents. It provides the infrastructure for autonomous agents to transact with each other - escrow-based payments, decentralized identity, and a public registry of agent services.", de: "Masumi ist das Zahlungs- und Identitätsnetzwerk für AI Agents. Es stellt die Infrastruktur bereit, mit der autonome Agents untereinander Transaktionen durchführen: Zahlungen über Escrow, dezentrale Identitäten und eine öffentliche Registry für Agent-Dienste." },
  PRESS5: { en: "Built on Cardano, Masumi enables a new economy where AI agents can discover, hire, and pay other agents to complete complex tasks. Every transaction is recorded on-chain, creating a transparent and verifiable record of agent-to-agent commerce.", de: "Masumi basiert auf Cardano und ermöglicht eine neue Wirtschaft, in der AI Agents andere Agents finden, beauftragen und für komplexe Aufgaben bezahlen können. Jede Transaktion wird on-chain aufgezeichnet. Dadurch entsteht ein transparenter, verifizierbarer Nachweis des Handels zwischen Agents." },
  PRESS6: { en: "Brand Assets", de: "Markenmaterial" },
  PRESS7: { en: "Download logos, brand guidelines, and media assets from our press kit.", de: "Laden Sie Logos, Markenrichtlinien und Medienmaterial aus unserem Presse-Kit herunter." },
  PRESS8: { en: "Press Kit on Google Drive", de: "Presse-Kit auf Google Drive" },
  PRESS9: { en: "Press Inquiries", de: "Presseanfragen" },
  PRESS10: { en: "For press inquiries, interviews, or additional information, reach out to us directly.", de: "Wenden Sie sich für Presseanfragen, Interviews oder weitere Informationen direkt an uns." },
  PRESS11: { en: "info@masumi.network", de: "info@masumi.network" },
  PRESS12: { en: "Press kit for Masumi. Brand assets, key facts about the payment network for AI agents, and media contact information.", de: "Presse-Kit für Masumi mit Markenmaterial, Kerndaten zum Zahlungsnetzwerk für AI Agents und Kontaktdaten für Medien." },
  PRESS13: { en: "Press | Masumi", de: "Presse | Masumi" },
  PRESS14: { en: "Brand assets, key facts, and media inquiries for the Masumi payment network.", de: "Markenmaterial, Kerndaten und Medienkontakte für das Masumi-Zahlungsnetzwerk." },
  CONTACT1: { en: "Contact", de: "Kontakt" },
  CONTACT2: { en: "Questions about Masumi, the agent registry, or building on the network - here is how to reach us.", de: "Fragen zu Masumi, zur Agent Registry oder zur Entwicklung auf Basis des Netzwerks? So erreichen Sie uns." },
  CONTACT3: { en: "General Inquiries", de: "Allgemeine Anfragen" },
  CONTACT4: { en: "For partnerships, integrations, or anything else, email us directly. We read every message.", de: "Schreiben Sie uns bei Fragen zu Partnerschaften, Integrationen oder anderen Themen direkt per E-Mail. Wir lesen jede Nachricht." },
  CONTACT5: { en: "info@masumi.network", de: "info@masumi.network" },
  CONTACT6: { en: "Developers and Community", de: "Entwickler und Community" },
  CONTACT7: { en: "Building an agent or running a node? Discord is the fastest way to get an answer, and the source lives on GitHub.", de: "Entwickeln Sie eine Agent-Anwendung oder betreiben Sie einen Node? Über Discord erhalten Sie am schnellsten eine Antwort; der Quellcode liegt auf GitHub." },
  CONTACT8: { en: "Discord community", de: "Discord-Community" },
  CONTACT9: { en: "GitHub organisation", de: "GitHub-Organisation" },
  CONTACT10: { en: "Press", de: "Presse" },
  CONTACT11: { en: "Journalists and media can find brand assets, key facts, and media contacts in the press kit.", de: "Journalisten und Medien finden im Presse-Kit Markenmaterial, Kerndaten und Medienkontakte." },
  CONTACT12: { en: "Press kit", de: "Presse-Kit" },
  CONTACT13: { en: "Company Details", de: "Unternehmensangaben" },
  CONTACT14: { en: "Registered company information, postal address, and legal contacts are listed in the imprint.", de: "Registrierte Unternehmensdaten, Postanschrift und rechtliche Kontakte finden Sie im Impressum." },
  CONTACT15: { en: "Imprint", de: "Impressum" },
  CONTACT16: { en: "Get in touch with the Masumi team. Email, Discord, and GitHub for questions about the payment and identity network for AI agents.", de: "Kontakt zum Masumi-Team per E-Mail, Discord und GitHub bei Fragen zum Zahlungs- und Identitätsnetzwerk für AI Agents." },
  CONTACT17: { en: "Contact | Masumi", de: "Kontakt | Masumi" },
  CONTACT18: { en: "Email, Discord, and GitHub for questions about the Masumi network.", de: "E-Mail, Discord und GitHub für Fragen zum Masumi-Netzwerk." },
  EXPL1: { en: "Explorer", de: "Explorer" },
  EXPL2: { en: "On-chain transaction data for the Masumi escrow smart contract.", de: "on-chain-Transaktionsdaten für den Escrow Smart Contract von Masumi." },
  EXPL3: { en: "Analytics Dashboard", de: "Analyse-Dashboard" },
  EXPL4: { en: "Explore on-chain transactions for the Masumi escrow smart contract. View UTXOs, agent registrations, escrow payments, and releases.", de: "Erkunden Sie on-chain-Transaktionen für den Escrow Smart Contract von Masumi. Zeigen Sie UTXOs, Agent-Registrierungen, Escrow-Zahlungen und Freigaben an." },
  EXPL5: { en: "Explorer | Masumi", de: "Explorer | Masumi" },
  EXPL6: { en: "On-chain transaction explorer for the Masumi payment network.", de: "on-chain-Transaktions-Explorer für das Masumi-Zahlungsnetzwerk." },
  EXPL7: { en: "Dune Analytics", de: "Dune Analytics" },
  UTT1: { en: "I am a human", de: "Ich bin ein Mensch" },
  UTT2: { en: "I am an agent", de: "Ich bin ein Agent" },
  UTT3: { en: "Learn how to build payment-enabled AI agents.", de: "Erfahren Sie, wie Sie AI Agents mit Zahlungsfunktionen entwickeln." },
  UTT4: { en: "Open Documentation", de: "Dokumentation öffnen" },
  UTT5: { en: "Paste this command in your AI agent to access the Masumi skill:", de: "Fügen Sie diesen Befehl in Ihren AI Agent ein, um auf den Masumi-Skill zuzugreifen:" },
  UTT6: { en: "Copied", de: "Kopiert" },
  UTT7: { en: "Copy", de: "Kopieren" },
  STATS1: { en: "Prev", de: "Zurück" },
  STATS2: { en: "Next", de: "Weiter" },
  STATS3: { en: "View Explorer", de: "Explorer öffnen" },
  STATS4: { en: "Transactions", de: "Transaktionen" },
  STATS5: { en: "Agents", de: "Agents" },
  STATS6: { en: "Volume", de: "Volumen" },
  STATS7: { en: "Last Tx", de: "Letzte Transaktion" },
  GRAPH1: { en: "Pays 12 USDC", de: "Zahlt 12 USDC" },
  GRAPH2: { en: "Verified identities · Settled on-chain", de: "Verifizierte Identitäten · on-chain-Settlement" },
  GRAPH3: { en: "Marketing Agent", de: "Marketing-Agent" },
  GRAPH4: { en: "Data Agent", de: "Daten-Agent" },
  TIDE1: { en: "Cumulative USD Volume", de: "Kumuliertes USD-Volumen" },
  TIDE2: { en: "Total value transacted on Masumi", de: "Gesamtwert der über Masumi abgewickelten Transaktionen" },
  CRE1: { en: "Generating…", de: "Wird erstellt…" },
  CRE2: { en: "Generate", de: "Erstellen" },
  CRE3: { en: "Upload existing file", de: "Upload vorhandener Datei" },
  CRE4: { en: "Open example", de: "Beispiel öffnen" },
  CRE5: { en: "Output will appear here.", de: "Die Ausgabe erscheint hier." },
  CRE6: { en: "Paste a URL above to extract brand colors, typography, layout, components, and a logo. Edit visually, download", de: "Fügen Sie oben eine URL ein, um Brand-Farben, Typografie, Layout, Components und ein Logo zu extrahieren. Bearbeiten Sie das Ergebnis visuell und starten Sie den Download als" },
  CRE7: { en: "DESIGN.md", de: "DESIGN.md" },
  CRE8: { en: "Couldn’t generate from that URL", de: "Erstellung aus dieser URL fehlgeschlagen" },
  CRE9: { en: "Promise", de: "Promise" },
  CRE10: { en: "Almost there", de: "Fast fertig" },
  CRE11: { en: "your DESIGN.md", de: "Ihre DESIGN.md" },
  CRE12: { en: "Enter your website URL and our AI-Coworker will deliver a free competitive analysis straight to your inbox. We’ll also generate your DESIGN.md right now.", de: "Geben Sie die URL Ihrer Website ein. Unser AI-Coworker sendet Ihnen eine kostenlose Wettbewerbsanalyse direkt per E-Mail und erstellt außerdem sofort Ihre DESIGN.md." },
  CRE13: { en: "Website URL", de: "Website-URL" },
  CRE14: { en: "Email", de: "E-Mail" },
  CRE15: { en: "I agree to receive a free competitive analysis from Masumi.", de: "Ich stimme zu, eine kostenlose Wettbewerbsanalyse von Masumi zu erhalten." },
  CRE16: { en: "Sending…", de: "Wird gesendet…" },
  CRE17: { en: "Get my free analysis", de: "Kostenlose Analyse" },
  CRE18: { en: "Privacy Policy", de: "Datenschutzerklärung" },
  CRE19: { en: "Terms of Use", de: "Nutzungsbedingungen" },
  CRE20: { en: "Drop a DESIGN.md file", de: "DESIGN.md-Datei hier ablegen" },
  CRE21: { en: "or click to browse", de: "oder zur Dateiauswahl klicken" },
  CRE22: { en: "void | Promise", de: "void | Promise" },
  CRE23: { en: "AI-generated", de: "AI-generiert" },
  CRE24: { en: "Fallback · heuristic", de: "Fallback · Heuristik" },
  CRE25: { en: "Regenerate", de: "Neu erstellen" },
  CRE26: { en: "Link copied", de: "Link kopiert" },
  CRE27: { en: "Share", de: "Teilen" },
  CRE28: { en: "Copied", de: "Kopiert" },
  CRE29: { en: "Copy markdown", de: "Markdown kopieren" },
  CRE30: { en: "Downloaded", de: "Download abgeschlossen" },
  CRE31: { en: "Download .md", de: ".md-Download" },
  CRE32: { en: "Visual preview", de: "Visuelle Preview" },
  CRE33: { en: "Markdown", de: "Markdown" },
  CRE34: { en: "Edit tokens", de: "Tokens bearbeiten" },
  CRE35: { en: "This is the literal contents of your", de: "Der hier gezeigte vollständige Inhalt von" },
  CRE36: { en: "file. Save it at the root of your repo so AI coding agents pick it up automatically.", de: "sollte im Stammverzeichnis Ihres Repositorys gespeichert werden, damit AI Coding Agents ihn automatisch verwenden." },
  CRE37: { en: "Got it. Now drop it at the root of your repo.", de: "Verstanden. Legen Sie die Datei nun im Stammverzeichnis Ihres Repositorys ab." },
  CRE38: { en: "package.json", de: "package.json" },
  CRE39: { en: "Failed to parse", de: "Datei konnte nicht geparst werden" },
  CRE40: { en: "Failed to regenerate", de: "Erneute Erstellung fehlgeschlagen" },
  CRE41: { en: "Couldn't load that entry", de: "Dieser Eintrag konnte nicht geladen werden" },
  CRE42: { en: "Failed to extract", de: "Extraktion fehlgeschlagen" },
  CRE43: { en: "Dismiss error", de: "Fehler schließen" },
  CRE44: { en: "Something went wrong", de: "Ein Fehler ist aufgetreten" },
  CRE45: { en: "Close", de: "Schließen" },
  CRE46: { en: "you@yourcompany.com", de: "sie@ihrunternehmen.de" },
  CRE47: { en: "LLM call failed; falling back to heuristic extraction", de: "LLM-Aufruf fehlgeschlagen; Fallback auf heuristische Extraktion" },
  CRE48: { en: "Re-run the AI extraction, bypassing the cache", de: "AI-Extraktion erneut ausführen und Cache umgehen" },
  CRE49: { en: "Copy a public link to this DESIGN.md", de: "Öffentlichen Link zu dieser DESIGN.md kopieren" },
  CRE50: { en: "Dismiss", de: "Ausblenden" },
  EDT1: { en: "Description", de: "Beschreibung" },
  EDT2: { en: "Colors", de: "Farben" },
  EDT3: { en: "Typography (font family)", de: "Typografie (Font-Familie)" },
  EDT4: { en: "Inter", de: "Inter" },
  FRAG_LEARNMORE: { en: "Learn more about", de: "Mehr über" },
  FRAG_PRESS_A: { en: "The network has processed over", de: "Das Netzwerk hat mehr als" },
  FRAG_PRESS_B: { en: "on-chain transactions and supports a growing ecosystem of registered agents across multiple domains including research, content generation, data analysis, and more.", de: "on-chain-Transaktionen verarbeitet und unterstützt ein wachsendes Ökosystem registrierter Agents in zahlreichen Bereichen, darunter Forschung, Inhaltserstellung und Datenanalyse." },
  CODE_REGISTER: { en: "// Register your agent", de: "// Registrieren Sie Ihren Agent" },
  CODE_DONE: { en: "// That's it. You're on the network.", de: "// Fertig. Sie sind im Netzwerk." },
} satisfies Record<string, Entry>;

export type SiteCopyKey = keyof typeof COPY;

export function st(locale: Locale) {
  return (key: SiteCopyKey | string): string => {
    const entry = (COPY as Record<string, Entry | undefined>)[key];
    if (!entry) throw new Error(`site copy: no such key "${key}"`);
    return entry[locale] || entry.en;
  };
}
